site_name: Openiclib
site_description: Openiclib is an open-source library for open-source PDK silicon-proven circuits and systems.
site_url: https://das-dias.github.io/openiclib/

hooks:
  - hooks/catalog_hook.py

extra_css:
  - assets/catalog.css

extra_javascript:
  - assets/catalog.js

nav:
  - Home: index.md
  - Library: library.md
  - Stats: stats.md
  - Technologies: technologies.md
  - Examples: examples.md
  - Submitting: submitting.md

theme:
  name: shadcn
  icon: null
  topbar_sections: false
  pygments_style:
    light: shadcn-light
    dark: github-dark
  katex_options:
    trust: true
    macros:
      "\\dx": "\\mathrm{d}x"
      "\\NN": "\\mathbb{N}"
  # show_datetime: true
  # accent: "oklch(64.5% 0.246 16.439)"

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  admonition:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:
  pymdownx.blocks.caption:
  shadcn.extensions.hover_card: